package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class FirmOfferPosition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.ex_change
     *
     * @mbg.generated
     */
    private String exChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.instrument_id
     *
     * @mbg.generated
     */
    private String instrumentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.trading_on
     *
     * @mbg.generated
     */
    private String tradingOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.margin_mode
     *
     * @mbg.generated
     */
    private String marginMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.position_date
     *
     * @mbg.generated
     */
    private Date positionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.liquidation_price
     *
     * @mbg.generated
     */
    private BigDecimal liquidationPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.qty
     *
     * @mbg.generated
     */
    private BigDecimal qty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.avail_qty
     *
     * @mbg.generated
     */
    private BigDecimal availQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.avg_cost
     *
     * @mbg.generated
     */
    private BigDecimal avgCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.settlement_price
     *
     * @mbg.generated
     */
    private BigDecimal settlementPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.liqui_price
     *
     * @mbg.generated
     */
    private BigDecimal liquiPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.pnl_ratio
     *
     * @mbg.generated
     */
    private BigDecimal pnlRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.margin
     *
     * @mbg.generated
     */
    private BigDecimal margin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.realized_pnl
     *
     * @mbg.generated
     */
    private BigDecimal realizedPnl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.leverage
     *
     * @mbg.generated
     */
    private String leverage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.utime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_position.current_cost
     *
     * @mbg.generated
     */
    private BigDecimal currentCost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.id
     *
     * @return the value of firm_offer_position.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.id
     *
     * @param id the value for firm_offer_position.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.user_id
     *
     * @return the value of firm_offer_position.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.user_id
     *
     * @param userId the value for firm_offer_position.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.ex_change
     *
     * @return the value of firm_offer_position.ex_change
     *
     * @mbg.generated
     */
    public String getExChange() {
        return exChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.ex_change
     *
     * @param exChange the value for firm_offer_position.ex_change
     *
     * @mbg.generated
     */
    public void setExChange(String exChange) {
        this.exChange = exChange == null ? null : exChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.instrument_id
     *
     * @return the value of firm_offer_position.instrument_id
     *
     * @mbg.generated
     */
    public String getInstrumentId() {
        return instrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.instrument_id
     *
     * @param instrumentId the value for firm_offer_position.instrument_id
     *
     * @mbg.generated
     */
    public void setInstrumentId(String instrumentId) {
        this.instrumentId = instrumentId == null ? null : instrumentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.trading_on
     *
     * @return the value of firm_offer_position.trading_on
     *
     * @mbg.generated
     */
    public String getTradingOn() {
        return tradingOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.trading_on
     *
     * @param tradingOn the value for firm_offer_position.trading_on
     *
     * @mbg.generated
     */
    public void setTradingOn(String tradingOn) {
        this.tradingOn = tradingOn == null ? null : tradingOn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.type
     *
     * @return the value of firm_offer_position.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.type
     *
     * @param type the value for firm_offer_position.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.margin_mode
     *
     * @return the value of firm_offer_position.margin_mode
     *
     * @mbg.generated
     */
    public String getMarginMode() {
        return marginMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.margin_mode
     *
     * @param marginMode the value for firm_offer_position.margin_mode
     *
     * @mbg.generated
     */
    public void setMarginMode(String marginMode) {
        this.marginMode = marginMode == null ? null : marginMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.position_date
     *
     * @return the value of firm_offer_position.position_date
     *
     * @mbg.generated
     */
    public Date getPositionDate() {
        return positionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.position_date
     *
     * @param positionDate the value for firm_offer_position.position_date
     *
     * @mbg.generated
     */
    public void setPositionDate(Date positionDate) {
        this.positionDate = positionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.liquidation_price
     *
     * @return the value of firm_offer_position.liquidation_price
     *
     * @mbg.generated
     */
    public BigDecimal getLiquidationPrice() {
        return liquidationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.liquidation_price
     *
     * @param liquidationPrice the value for firm_offer_position.liquidation_price
     *
     * @mbg.generated
     */
    public void setLiquidationPrice(BigDecimal liquidationPrice) {
        this.liquidationPrice = liquidationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.qty
     *
     * @return the value of firm_offer_position.qty
     *
     * @mbg.generated
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.qty
     *
     * @param qty the value for firm_offer_position.qty
     *
     * @mbg.generated
     */
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.avail_qty
     *
     * @return the value of firm_offer_position.avail_qty
     *
     * @mbg.generated
     */
    public BigDecimal getAvailQty() {
        return availQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.avail_qty
     *
     * @param availQty the value for firm_offer_position.avail_qty
     *
     * @mbg.generated
     */
    public void setAvailQty(BigDecimal availQty) {
        this.availQty = availQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.avg_cost
     *
     * @return the value of firm_offer_position.avg_cost
     *
     * @mbg.generated
     */
    public BigDecimal getAvgCost() {
        return avgCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.avg_cost
     *
     * @param avgCost the value for firm_offer_position.avg_cost
     *
     * @mbg.generated
     */
    public void setAvgCost(BigDecimal avgCost) {
        this.avgCost = avgCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.settlement_price
     *
     * @return the value of firm_offer_position.settlement_price
     *
     * @mbg.generated
     */
    public BigDecimal getSettlementPrice() {
        return settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.settlement_price
     *
     * @param settlementPrice the value for firm_offer_position.settlement_price
     *
     * @mbg.generated
     */
    public void setSettlementPrice(BigDecimal settlementPrice) {
        this.settlementPrice = settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.liqui_price
     *
     * @return the value of firm_offer_position.liqui_price
     *
     * @mbg.generated
     */
    public BigDecimal getLiquiPrice() {
        return liquiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.liqui_price
     *
     * @param liquiPrice the value for firm_offer_position.liqui_price
     *
     * @mbg.generated
     */
    public void setLiquiPrice(BigDecimal liquiPrice) {
        this.liquiPrice = liquiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.pnl_ratio
     *
     * @return the value of firm_offer_position.pnl_ratio
     *
     * @mbg.generated
     */
    public BigDecimal getPnlRatio() {
        return pnlRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.pnl_ratio
     *
     * @param pnlRatio the value for firm_offer_position.pnl_ratio
     *
     * @mbg.generated
     */
    public void setPnlRatio(BigDecimal pnlRatio) {
        this.pnlRatio = pnlRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.margin
     *
     * @return the value of firm_offer_position.margin
     *
     * @mbg.generated
     */
    public BigDecimal getMargin() {
        return margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.margin
     *
     * @param margin the value for firm_offer_position.margin
     *
     * @mbg.generated
     */
    public void setMargin(BigDecimal margin) {
        this.margin = margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.realized_pnl
     *
     * @return the value of firm_offer_position.realized_pnl
     *
     * @mbg.generated
     */
    public BigDecimal getRealizedPnl() {
        return realizedPnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.realized_pnl
     *
     * @param realizedPnl the value for firm_offer_position.realized_pnl
     *
     * @mbg.generated
     */
    public void setRealizedPnl(BigDecimal realizedPnl) {
        this.realizedPnl = realizedPnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.leverage
     *
     * @return the value of firm_offer_position.leverage
     *
     * @mbg.generated
     */
    public String getLeverage() {
        return leverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.leverage
     *
     * @param leverage the value for firm_offer_position.leverage
     *
     * @mbg.generated
     */
    public void setLeverage(String leverage) {
        this.leverage = leverage == null ? null : leverage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.utime
     *
     * @return the value of firm_offer_position.utime
     *
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.utime
     *
     * @param utime the value for firm_offer_position.utime
     *
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_position.current_cost
     *
     * @return the value of firm_offer_position.current_cost
     *
     * @mbg.generated
     */
    public BigDecimal getCurrentCost() {
        return currentCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_position.current_cost
     *
     * @param currentCost the value for firm_offer_position.current_cost
     *
     * @mbg.generated
     */
    public void setCurrentCost(BigDecimal currentCost) {
        this.currentCost = currentCost;
    }
}