package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class FirmOfferOrderHist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.order_status
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.ex_change
     *
     * @mbg.generated
     */
    private String exChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.trading_on
     *
     * @mbg.generated
     */
    private String tradingOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.side
     *
     * @mbg.generated
     */
    private String side;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.field_amount
     *
     * @mbg.generated
     */
    private BigDecimal fieldAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.field_price
     *
     * @mbg.generated
     */
    private BigDecimal fieldPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.order_date
     *
     * @mbg.generated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.contract_name
     *
     * @mbg.generated
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.fee
     *
     * @mbg.generated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.unit_amount
     *
     * @mbg.generated
     */
    private BigDecimal unitAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.lever_rate
     *
     * @mbg.generated
     */
    private BigDecimal leverRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.utime
     *
     * @mbg.generated
     */
    private Date utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_order_hist.push_states
     *
     * @mbg.generated
     */
    private Integer pushStates;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.id
     *
     * @return the value of firm_offer_order_hist.id
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.id
     *
     * @param id the value for firm_offer_order_hist.id
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.user_id
     *
     * @return the value of firm_offer_order_hist.user_id
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.user_id
     *
     * @param userId the value for firm_offer_order_hist.user_id
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.order_status
     *
     * @return the value of firm_offer_order_hist.order_status
     * @mbg.generated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.order_status
     *
     * @param orderStatus the value for firm_offer_order_hist.order_status
     * @mbg.generated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.ex_change
     *
     * @return the value of firm_offer_order_hist.ex_change
     * @mbg.generated
     */
    public String getExChange() {
        return exChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.ex_change
     *
     * @param exChange the value for firm_offer_order_hist.ex_change
     * @mbg.generated
     */
    public void setExChange(String exChange) {
        this.exChange = exChange == null ? null : exChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.trading_on
     *
     * @return the value of firm_offer_order_hist.trading_on
     * @mbg.generated
     */
    public String getTradingOn() {
        return tradingOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.trading_on
     *
     * @param tradingOn the value for firm_offer_order_hist.trading_on
     * @mbg.generated
     */
    public void setTradingOn(String tradingOn) {
        this.tradingOn = tradingOn == null ? null : tradingOn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.type
     *
     * @return the value of firm_offer_order_hist.type
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.type
     *
     * @param type the value for firm_offer_order_hist.type
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.price
     *
     * @return the value of firm_offer_order_hist.price
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.price
     *
     * @param price the value for firm_offer_order_hist.price
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.side
     *
     * @return the value of firm_offer_order_hist.side
     * @mbg.generated
     */
    public String getSide() {
        return side;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.side
     *
     * @param side the value for firm_offer_order_hist.side
     * @mbg.generated
     */
    public void setSide(String side) {
        this.side = side == null ? null : side.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.amount
     *
     * @return the value of firm_offer_order_hist.amount
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.amount
     *
     * @param amount the value for firm_offer_order_hist.amount
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.field_amount
     *
     * @return the value of firm_offer_order_hist.field_amount
     * @mbg.generated
     */
    public BigDecimal getFieldAmount() {
        return fieldAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.field_amount
     *
     * @param fieldAmount the value for firm_offer_order_hist.field_amount
     * @mbg.generated
     */
    public void setFieldAmount(BigDecimal fieldAmount) {
        this.fieldAmount = fieldAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.field_price
     *
     * @return the value of firm_offer_order_hist.field_price
     * @mbg.generated
     */
    public BigDecimal getFieldPrice() {
        return fieldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.field_price
     *
     * @param fieldPrice the value for firm_offer_order_hist.field_price
     * @mbg.generated
     */
    public void setFieldPrice(BigDecimal fieldPrice) {
        this.fieldPrice = fieldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.order_date
     *
     * @return the value of firm_offer_order_hist.order_date
     * @mbg.generated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.order_date
     *
     * @param orderDate the value for firm_offer_order_hist.order_date
     * @mbg.generated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.contract_name
     *
     * @return the value of firm_offer_order_hist.contract_name
     * @mbg.generated
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.contract_name
     *
     * @param contractName the value for firm_offer_order_hist.contract_name
     * @mbg.generated
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.fee
     *
     * @return the value of firm_offer_order_hist.fee
     * @mbg.generated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.fee
     *
     * @param fee the value for firm_offer_order_hist.fee
     * @mbg.generated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.unit_amount
     *
     * @return the value of firm_offer_order_hist.unit_amount
     * @mbg.generated
     */
    public BigDecimal getUnitAmount() {
        return unitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.unit_amount
     *
     * @param unitAmount the value for firm_offer_order_hist.unit_amount
     * @mbg.generated
     */
    public void setUnitAmount(BigDecimal unitAmount) {
        this.unitAmount = unitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.lever_rate
     *
     * @return the value of firm_offer_order_hist.lever_rate
     * @mbg.generated
     */
    public BigDecimal getLeverRate() {
        return leverRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.lever_rate
     *
     * @param leverRate the value for firm_offer_order_hist.lever_rate
     * @mbg.generated
     */
    public void setLeverRate(BigDecimal leverRate) {
        this.leverRate = leverRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.utime
     *
     * @return the value of firm_offer_order_hist.utime
     * @mbg.generated
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.utime
     *
     * @param utime the value for firm_offer_order_hist.utime
     * @mbg.generated
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_order_hist.push_states
     *
     * @return the value of firm_offer_order_hist.push_states
     * @mbg.generated
     */
    public Integer getPushStates() {
        return pushStates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_order_hist.push_states
     *
     * @param pushStates the value for firm_offer_order_hist.push_states
     * @mbg.generated
     */
    public void setPushStates(Integer pushStates) {
        this.pushStates = pushStates;
    }
}