package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FirmOfferMatchHistExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public FirmOfferMatchHistExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andMatchIdIsNull() {
            addCriterion("match_id is null");
            return (Criteria) this;
        }

        public Criteria andMatchIdIsNotNull() {
            addCriterion("match_id is not null");
            return (Criteria) this;
        }

        public Criteria andMatchIdEqualTo(Long value) {
            addCriterion("match_id =", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdNotEqualTo(Long value) {
            addCriterion("match_id <>", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdGreaterThan(Long value) {
            addCriterion("match_id >", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdGreaterThanOrEqualTo(Long value) {
            addCriterion("match_id >=", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdLessThan(Long value) {
            addCriterion("match_id <", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdLessThanOrEqualTo(Long value) {
            addCriterion("match_id <=", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdIn(List<Long> values) {
            addCriterion("match_id in", values, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdNotIn(List<Long> values) {
            addCriterion("match_id not in", values, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdBetween(Long value1, Long value2) {
            addCriterion("match_id between", value1, value2, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdNotBetween(Long value1, Long value2) {
            addCriterion("match_id not between", value1, value2, "matchId");
            return (Criteria) this;
        }

        public Criteria andExChangeIsNull() {
            addCriterion("ex_change is null");
            return (Criteria) this;
        }

        public Criteria andExChangeIsNotNull() {
            addCriterion("ex_change is not null");
            return (Criteria) this;
        }

        public Criteria andExChangeEqualTo(String value) {
            addCriterion("ex_change =", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotEqualTo(String value) {
            addCriterion("ex_change <>", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeGreaterThan(String value) {
            addCriterion("ex_change >", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeGreaterThanOrEqualTo(String value) {
            addCriterion("ex_change >=", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeLessThan(String value) {
            addCriterion("ex_change <", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeLessThanOrEqualTo(String value) {
            addCriterion("ex_change <=", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeLike(String value) {
            addCriterion("ex_change like", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotLike(String value) {
            addCriterion("ex_change not like", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeIn(List<String> values) {
            addCriterion("ex_change in", values, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotIn(List<String> values) {
            addCriterion("ex_change not in", values, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeBetween(String value1, String value2) {
            addCriterion("ex_change between", value1, value2, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotBetween(String value1, String value2) {
            addCriterion("ex_change not between", value1, value2, "exChange");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNull() {
            addCriterion("symbol is null");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNotNull() {
            addCriterion("symbol is not null");
            return (Criteria) this;
        }

        public Criteria andSymbolEqualTo(String value) {
            addCriterion("symbol =", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotEqualTo(String value) {
            addCriterion("symbol <>", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThan(String value) {
            addCriterion("symbol >", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("symbol >=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThan(String value) {
            addCriterion("symbol <", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThanOrEqualTo(String value) {
            addCriterion("symbol <=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLike(String value) {
            addCriterion("symbol like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotLike(String value) {
            addCriterion("symbol not like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolIn(List<String> values) {
            addCriterion("symbol in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotIn(List<String> values) {
            addCriterion("symbol not in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolBetween(String value1, String value2) {
            addCriterion("symbol between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotBetween(String value1, String value2) {
            addCriterion("symbol not between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andFieldFeesIsNull() {
            addCriterion("field_fees is null");
            return (Criteria) this;
        }

        public Criteria andFieldFeesIsNotNull() {
            addCriterion("field_fees is not null");
            return (Criteria) this;
        }

        public Criteria andFieldFeesEqualTo(BigDecimal value) {
            addCriterion("field_fees =", value, "fieldFees");
            return (Criteria) this;
        }

        public Criteria andFieldFeesNotEqualTo(BigDecimal value) {
            addCriterion("field_fees <>", value, "fieldFees");
            return (Criteria) this;
        }

        public Criteria andFieldFeesGreaterThan(BigDecimal value) {
            addCriterion("field_fees >", value, "fieldFees");
            return (Criteria) this;
        }

        public Criteria andFieldFeesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("field_fees >=", value, "fieldFees");
            return (Criteria) this;
        }

        public Criteria andFieldFeesLessThan(BigDecimal value) {
            addCriterion("field_fees <", value, "fieldFees");
            return (Criteria) this;
        }

        public Criteria andFieldFeesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("field_fees <=", value, "fieldFees");
            return (Criteria) this;
        }

        public Criteria andFieldFeesIn(List<BigDecimal> values) {
            addCriterion("field_fees in", values, "fieldFees");
            return (Criteria) this;
        }

        public Criteria andFieldFeesNotIn(List<BigDecimal> values) {
            addCriterion("field_fees not in", values, "fieldFees");
            return (Criteria) this;
        }

        public Criteria andFieldFeesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field_fees between", value1, value2, "fieldFees");
            return (Criteria) this;
        }

        public Criteria andFieldFeesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field_fees not between", value1, value2, "fieldFees");
            return (Criteria) this;
        }

        public Criteria andFieldAmountIsNull() {
            addCriterion("field_amount is null");
            return (Criteria) this;
        }

        public Criteria andFieldAmountIsNotNull() {
            addCriterion("field_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFieldAmountEqualTo(BigDecimal value) {
            addCriterion("field_amount =", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountNotEqualTo(BigDecimal value) {
            addCriterion("field_amount <>", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountGreaterThan(BigDecimal value) {
            addCriterion("field_amount >", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("field_amount >=", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountLessThan(BigDecimal value) {
            addCriterion("field_amount <", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("field_amount <=", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountIn(List<BigDecimal> values) {
            addCriterion("field_amount in", values, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountNotIn(List<BigDecimal> values) {
            addCriterion("field_amount not in", values, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field_amount between", value1, value2, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field_amount not between", value1, value2, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldPriceIsNull() {
            addCriterion("field_price is null");
            return (Criteria) this;
        }

        public Criteria andFieldPriceIsNotNull() {
            addCriterion("field_price is not null");
            return (Criteria) this;
        }

        public Criteria andFieldPriceEqualTo(BigDecimal value) {
            addCriterion("field_price =", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceNotEqualTo(BigDecimal value) {
            addCriterion("field_price <>", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceGreaterThan(BigDecimal value) {
            addCriterion("field_price >", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("field_price >=", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceLessThan(BigDecimal value) {
            addCriterion("field_price <", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("field_price <=", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceIn(List<BigDecimal> values) {
            addCriterion("field_price in", values, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceNotIn(List<BigDecimal> values) {
            addCriterion("field_price not in", values, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field_price between", value1, value2, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field_price not between", value1, value2, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andMatchDateIsNull() {
            addCriterion("match_date is null");
            return (Criteria) this;
        }

        public Criteria andMatchDateIsNotNull() {
            addCriterion("match_date is not null");
            return (Criteria) this;
        }

        public Criteria andMatchDateEqualTo(Date value) {
            addCriterion("match_date =", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateNotEqualTo(Date value) {
            addCriterion("match_date <>", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateGreaterThan(Date value) {
            addCriterion("match_date >", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateGreaterThanOrEqualTo(Date value) {
            addCriterion("match_date >=", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateLessThan(Date value) {
            addCriterion("match_date <", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateLessThanOrEqualTo(Date value) {
            addCriterion("match_date <=", value, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateIn(List<Date> values) {
            addCriterion("match_date in", values, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateNotIn(List<Date> values) {
            addCriterion("match_date not in", values, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateBetween(Date value1, Date value2) {
            addCriterion("match_date between", value1, value2, "matchDate");
            return (Criteria) this;
        }

        public Criteria andMatchDateNotBetween(Date value1, Date value2) {
            addCriterion("match_date not between", value1, value2, "matchDate");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNull() {
            addCriterion("utime is null");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNotNull() {
            addCriterion("utime is not null");
            return (Criteria) this;
        }

        public Criteria andUtimeEqualTo(Date value) {
            addCriterion("utime =", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotEqualTo(Date value) {
            addCriterion("utime <>", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThan(Date value) {
            addCriterion("utime >", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("utime >=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThan(Date value) {
            addCriterion("utime <", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThanOrEqualTo(Date value) {
            addCriterion("utime <=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeIn(List<Date> values) {
            addCriterion("utime in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotIn(List<Date> values) {
            addCriterion("utime not in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeBetween(Date value1, Date value2) {
            addCriterion("utime between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotBetween(Date value1, Date value2) {
            addCriterion("utime not between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andMatchTypeIsNull() {
            addCriterion("match_type is null");
            return (Criteria) this;
        }

        public Criteria andMatchTypeIsNotNull() {
            addCriterion("match_type is not null");
            return (Criteria) this;
        }

        public Criteria andMatchTypeEqualTo(String value) {
            addCriterion("match_type =", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotEqualTo(String value) {
            addCriterion("match_type <>", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeGreaterThan(String value) {
            addCriterion("match_type >", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeGreaterThanOrEqualTo(String value) {
            addCriterion("match_type >=", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeLessThan(String value) {
            addCriterion("match_type <", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeLessThanOrEqualTo(String value) {
            addCriterion("match_type <=", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeLike(String value) {
            addCriterion("match_type like", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotLike(String value) {
            addCriterion("match_type not like", value, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeIn(List<String> values) {
            addCriterion("match_type in", values, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotIn(List<String> values) {
            addCriterion("match_type not in", values, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeBetween(String value1, String value2) {
            addCriterion("match_type between", value1, value2, "matchType");
            return (Criteria) this;
        }

        public Criteria andMatchTypeNotBetween(String value1, String value2) {
            addCriterion("match_type not between", value1, value2, "matchType");
            return (Criteria) this;
        }

        public Criteria andPushStatesIsNull() {
            addCriterion("push_states is null");
            return (Criteria) this;
        }

        public Criteria andPushStatesIsNotNull() {
            addCriterion("push_states is not null");
            return (Criteria) this;
        }

        public Criteria andPushStatesEqualTo(Integer value) {
            addCriterion("push_states =", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesNotEqualTo(Integer value) {
            addCriterion("push_states <>", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesGreaterThan(Integer value) {
            addCriterion("push_states >", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesGreaterThanOrEqualTo(Integer value) {
            addCriterion("push_states >=", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesLessThan(Integer value) {
            addCriterion("push_states <", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesLessThanOrEqualTo(Integer value) {
            addCriterion("push_states <=", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesIn(List<Integer> values) {
            addCriterion("push_states in", values, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesNotIn(List<Integer> values) {
            addCriterion("push_states not in", values, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesBetween(Integer value1, Integer value2) {
            addCriterion("push_states between", value1, value2, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesNotBetween(Integer value1, Integer value2) {
            addCriterion("push_states not between", value1, value2, "pushStates");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_match_hist
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}