package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FirmOfferOrderHistExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public FirmOfferOrderHistExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(Integer value) {
            addCriterion("order_status =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(Integer value) {
            addCriterion("order_status <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(Integer value) {
            addCriterion("order_status >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_status >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(Integer value) {
            addCriterion("order_status <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("order_status <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<Integer> values) {
            addCriterion("order_status in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<Integer> values) {
            addCriterion("order_status not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("order_status between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("order_status not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andExChangeIsNull() {
            addCriterion("ex_change is null");
            return (Criteria) this;
        }

        public Criteria andExChangeIsNotNull() {
            addCriterion("ex_change is not null");
            return (Criteria) this;
        }

        public Criteria andExChangeEqualTo(String value) {
            addCriterion("ex_change =", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotEqualTo(String value) {
            addCriterion("ex_change <>", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeGreaterThan(String value) {
            addCriterion("ex_change >", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeGreaterThanOrEqualTo(String value) {
            addCriterion("ex_change >=", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeLessThan(String value) {
            addCriterion("ex_change <", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeLessThanOrEqualTo(String value) {
            addCriterion("ex_change <=", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeLike(String value) {
            addCriterion("ex_change like", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotLike(String value) {
            addCriterion("ex_change not like", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeIn(List<String> values) {
            addCriterion("ex_change in", values, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotIn(List<String> values) {
            addCriterion("ex_change not in", values, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeBetween(String value1, String value2) {
            addCriterion("ex_change between", value1, value2, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotBetween(String value1, String value2) {
            addCriterion("ex_change not between", value1, value2, "exChange");
            return (Criteria) this;
        }

        public Criteria andTradingOnIsNull() {
            addCriterion("trading_on is null");
            return (Criteria) this;
        }

        public Criteria andTradingOnIsNotNull() {
            addCriterion("trading_on is not null");
            return (Criteria) this;
        }

        public Criteria andTradingOnEqualTo(String value) {
            addCriterion("trading_on =", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnNotEqualTo(String value) {
            addCriterion("trading_on <>", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnGreaterThan(String value) {
            addCriterion("trading_on >", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnGreaterThanOrEqualTo(String value) {
            addCriterion("trading_on >=", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnLessThan(String value) {
            addCriterion("trading_on <", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnLessThanOrEqualTo(String value) {
            addCriterion("trading_on <=", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnLike(String value) {
            addCriterion("trading_on like", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnNotLike(String value) {
            addCriterion("trading_on not like", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnIn(List<String> values) {
            addCriterion("trading_on in", values, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnNotIn(List<String> values) {
            addCriterion("trading_on not in", values, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnBetween(String value1, String value2) {
            addCriterion("trading_on between", value1, value2, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnNotBetween(String value1, String value2) {
            addCriterion("trading_on not between", value1, value2, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andSideIsNull() {
            addCriterion("side is null");
            return (Criteria) this;
        }

        public Criteria andSideIsNotNull() {
            addCriterion("side is not null");
            return (Criteria) this;
        }

        public Criteria andSideEqualTo(String value) {
            addCriterion("side =", value, "side");
            return (Criteria) this;
        }

        public Criteria andSideNotEqualTo(String value) {
            addCriterion("side <>", value, "side");
            return (Criteria) this;
        }

        public Criteria andSideGreaterThan(String value) {
            addCriterion("side >", value, "side");
            return (Criteria) this;
        }

        public Criteria andSideGreaterThanOrEqualTo(String value) {
            addCriterion("side >=", value, "side");
            return (Criteria) this;
        }

        public Criteria andSideLessThan(String value) {
            addCriterion("side <", value, "side");
            return (Criteria) this;
        }

        public Criteria andSideLessThanOrEqualTo(String value) {
            addCriterion("side <=", value, "side");
            return (Criteria) this;
        }

        public Criteria andSideLike(String value) {
            addCriterion("side like", value, "side");
            return (Criteria) this;
        }

        public Criteria andSideNotLike(String value) {
            addCriterion("side not like", value, "side");
            return (Criteria) this;
        }

        public Criteria andSideIn(List<String> values) {
            addCriterion("side in", values, "side");
            return (Criteria) this;
        }

        public Criteria andSideNotIn(List<String> values) {
            addCriterion("side not in", values, "side");
            return (Criteria) this;
        }

        public Criteria andSideBetween(String value1, String value2) {
            addCriterion("side between", value1, value2, "side");
            return (Criteria) this;
        }

        public Criteria andSideNotBetween(String value1, String value2) {
            addCriterion("side not between", value1, value2, "side");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountIsNull() {
            addCriterion("field_amount is null");
            return (Criteria) this;
        }

        public Criteria andFieldAmountIsNotNull() {
            addCriterion("field_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFieldAmountEqualTo(BigDecimal value) {
            addCriterion("field_amount =", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountNotEqualTo(BigDecimal value) {
            addCriterion("field_amount <>", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountGreaterThan(BigDecimal value) {
            addCriterion("field_amount >", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("field_amount >=", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountLessThan(BigDecimal value) {
            addCriterion("field_amount <", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("field_amount <=", value, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountIn(List<BigDecimal> values) {
            addCriterion("field_amount in", values, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountNotIn(List<BigDecimal> values) {
            addCriterion("field_amount not in", values, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field_amount between", value1, value2, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field_amount not between", value1, value2, "fieldAmount");
            return (Criteria) this;
        }

        public Criteria andFieldPriceIsNull() {
            addCriterion("field_price is null");
            return (Criteria) this;
        }

        public Criteria andFieldPriceIsNotNull() {
            addCriterion("field_price is not null");
            return (Criteria) this;
        }

        public Criteria andFieldPriceEqualTo(BigDecimal value) {
            addCriterion("field_price =", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceNotEqualTo(BigDecimal value) {
            addCriterion("field_price <>", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceGreaterThan(BigDecimal value) {
            addCriterion("field_price >", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("field_price >=", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceLessThan(BigDecimal value) {
            addCriterion("field_price <", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("field_price <=", value, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceIn(List<BigDecimal> values) {
            addCriterion("field_price in", values, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceNotIn(List<BigDecimal> values) {
            addCriterion("field_price not in", values, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field_price between", value1, value2, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andFieldPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("field_price not between", value1, value2, "fieldPrice");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNull() {
            addCriterion("order_date is null");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNotNull() {
            addCriterion("order_date is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDateEqualTo(Date value) {
            addCriterion("order_date =", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotEqualTo(Date value) {
            addCriterion("order_date <>", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThan(Date value) {
            addCriterion("order_date >", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThanOrEqualTo(Date value) {
            addCriterion("order_date >=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThan(Date value) {
            addCriterion("order_date <", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThanOrEqualTo(Date value) {
            addCriterion("order_date <=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateIn(List<Date> values) {
            addCriterion("order_date in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotIn(List<Date> values) {
            addCriterion("order_date not in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateBetween(Date value1, Date value2) {
            addCriterion("order_date between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotBetween(Date value1, Date value2) {
            addCriterion("order_date not between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNull() {
            addCriterion("contract_name is null");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNotNull() {
            addCriterion("contract_name is not null");
            return (Criteria) this;
        }

        public Criteria andContractNameEqualTo(String value) {
            addCriterion("contract_name =", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotEqualTo(String value) {
            addCriterion("contract_name <>", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThan(String value) {
            addCriterion("contract_name >", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThanOrEqualTo(String value) {
            addCriterion("contract_name >=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThan(String value) {
            addCriterion("contract_name <", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThanOrEqualTo(String value) {
            addCriterion("contract_name <=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLike(String value) {
            addCriterion("contract_name like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotLike(String value) {
            addCriterion("contract_name not like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameIn(List<String> values) {
            addCriterion("contract_name in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotIn(List<String> values) {
            addCriterion("contract_name not in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameBetween(String value1, String value2) {
            addCriterion("contract_name between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotBetween(String value1, String value2) {
            addCriterion("contract_name not between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andFeeIsNull() {
            addCriterion("fee is null");
            return (Criteria) this;
        }

        public Criteria andFeeIsNotNull() {
            addCriterion("fee is not null");
            return (Criteria) this;
        }

        public Criteria andFeeEqualTo(BigDecimal value) {
            addCriterion("fee =", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotEqualTo(BigDecimal value) {
            addCriterion("fee <>", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThan(BigDecimal value) {
            addCriterion("fee >", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fee >=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThan(BigDecimal value) {
            addCriterion("fee <", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fee <=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeIn(List<BigDecimal> values) {
            addCriterion("fee in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotIn(List<BigDecimal> values) {
            addCriterion("fee not in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fee between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fee not between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andUnitAmountIsNull() {
            addCriterion("unit_amount is null");
            return (Criteria) this;
        }

        public Criteria andUnitAmountIsNotNull() {
            addCriterion("unit_amount is not null");
            return (Criteria) this;
        }

        public Criteria andUnitAmountEqualTo(BigDecimal value) {
            addCriterion("unit_amount =", value, "unitAmount");
            return (Criteria) this;
        }

        public Criteria andUnitAmountNotEqualTo(BigDecimal value) {
            addCriterion("unit_amount <>", value, "unitAmount");
            return (Criteria) this;
        }

        public Criteria andUnitAmountGreaterThan(BigDecimal value) {
            addCriterion("unit_amount >", value, "unitAmount");
            return (Criteria) this;
        }

        public Criteria andUnitAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("unit_amount >=", value, "unitAmount");
            return (Criteria) this;
        }

        public Criteria andUnitAmountLessThan(BigDecimal value) {
            addCriterion("unit_amount <", value, "unitAmount");
            return (Criteria) this;
        }

        public Criteria andUnitAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("unit_amount <=", value, "unitAmount");
            return (Criteria) this;
        }

        public Criteria andUnitAmountIn(List<BigDecimal> values) {
            addCriterion("unit_amount in", values, "unitAmount");
            return (Criteria) this;
        }

        public Criteria andUnitAmountNotIn(List<BigDecimal> values) {
            addCriterion("unit_amount not in", values, "unitAmount");
            return (Criteria) this;
        }

        public Criteria andUnitAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("unit_amount between", value1, value2, "unitAmount");
            return (Criteria) this;
        }

        public Criteria andUnitAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("unit_amount not between", value1, value2, "unitAmount");
            return (Criteria) this;
        }

        public Criteria andLeverRateIsNull() {
            addCriterion("lever_rate is null");
            return (Criteria) this;
        }

        public Criteria andLeverRateIsNotNull() {
            addCriterion("lever_rate is not null");
            return (Criteria) this;
        }

        public Criteria andLeverRateEqualTo(BigDecimal value) {
            addCriterion("lever_rate =", value, "leverRate");
            return (Criteria) this;
        }

        public Criteria andLeverRateNotEqualTo(BigDecimal value) {
            addCriterion("lever_rate <>", value, "leverRate");
            return (Criteria) this;
        }

        public Criteria andLeverRateGreaterThan(BigDecimal value) {
            addCriterion("lever_rate >", value, "leverRate");
            return (Criteria) this;
        }

        public Criteria andLeverRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("lever_rate >=", value, "leverRate");
            return (Criteria) this;
        }

        public Criteria andLeverRateLessThan(BigDecimal value) {
            addCriterion("lever_rate <", value, "leverRate");
            return (Criteria) this;
        }

        public Criteria andLeverRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("lever_rate <=", value, "leverRate");
            return (Criteria) this;
        }

        public Criteria andLeverRateIn(List<BigDecimal> values) {
            addCriterion("lever_rate in", values, "leverRate");
            return (Criteria) this;
        }

        public Criteria andLeverRateNotIn(List<BigDecimal> values) {
            addCriterion("lever_rate not in", values, "leverRate");
            return (Criteria) this;
        }

        public Criteria andLeverRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lever_rate between", value1, value2, "leverRate");
            return (Criteria) this;
        }

        public Criteria andLeverRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lever_rate not between", value1, value2, "leverRate");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNull() {
            addCriterion("utime is null");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNotNull() {
            addCriterion("utime is not null");
            return (Criteria) this;
        }

        public Criteria andUtimeEqualTo(Date value) {
            addCriterion("utime =", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotEqualTo(Date value) {
            addCriterion("utime <>", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThan(Date value) {
            addCriterion("utime >", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("utime >=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThan(Date value) {
            addCriterion("utime <", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThanOrEqualTo(Date value) {
            addCriterion("utime <=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeIn(List<Date> values) {
            addCriterion("utime in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotIn(List<Date> values) {
            addCriterion("utime not in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeBetween(Date value1, Date value2) {
            addCriterion("utime between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotBetween(Date value1, Date value2) {
            addCriterion("utime not between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andPushStatesIsNull() {
            addCriterion("push_states is null");
            return (Criteria) this;
        }

        public Criteria andPushStatesIsNotNull() {
            addCriterion("push_states is not null");
            return (Criteria) this;
        }

        public Criteria andPushStatesEqualTo(Integer value) {
            addCriterion("push_states =", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesNotEqualTo(Integer value) {
            addCriterion("push_states <>", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesGreaterThan(Integer value) {
            addCriterion("push_states >", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesGreaterThanOrEqualTo(Integer value) {
            addCriterion("push_states >=", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesLessThan(Integer value) {
            addCriterion("push_states <", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesLessThanOrEqualTo(Integer value) {
            addCriterion("push_states <=", value, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesIn(List<Integer> values) {
            addCriterion("push_states in", values, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesNotIn(List<Integer> values) {
            addCriterion("push_states not in", values, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesBetween(Integer value1, Integer value2) {
            addCriterion("push_states between", value1, value2, "pushStates");
            return (Criteria) this;
        }

        public Criteria andPushStatesNotBetween(Integer value1, Integer value2) {
            addCriterion("push_states not between", value1, value2, "pushStates");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_order_hist
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}