package com.ailu.firmoffer.dao.bean;

public class FirmOfferKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_key.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_key.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_key.ex_change
     *
     * @mbg.generated
     */
    private String exChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_key.apiKey
     *
     * @mbg.generated
     */
    private String apikey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_key.apiKeySecret
     *
     * @mbg.generated
     */
    private String apikeysecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_key.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_key.passphrase
     *
     * @mbg.generated
     */
    private String passphrase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_key.numberOfDays
     *
     * @mbg.generated
     */
    private Integer numberofdays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_key.spider_num
     *
     * @mbg.generated
     */
    private Integer spiderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_key.id
     *
     * @return the value of firm_offer_key.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_key.id
     *
     * @param id the value for firm_offer_key.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_key.user_id
     *
     * @return the value of firm_offer_key.user_id
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_key.user_id
     *
     * @param userId the value for firm_offer_key.user_id
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_key.ex_change
     *
     * @return the value of firm_offer_key.ex_change
     * @mbg.generated
     */
    public String getExChange() {
        return exChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_key.ex_change
     *
     * @param exChange the value for firm_offer_key.ex_change
     * @mbg.generated
     */
    public void setExChange(String exChange) {
        this.exChange = exChange == null ? null : exChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_key.apiKey
     *
     * @return the value of firm_offer_key.apiKey
     * @mbg.generated
     */
    public String getApikey() {
        return apikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_key.apiKey
     *
     * @param apikey the value for firm_offer_key.apiKey
     * @mbg.generated
     */
    public void setApikey(String apikey) {
        this.apikey = apikey == null ? null : apikey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_key.apiKeySecret
     *
     * @return the value of firm_offer_key.apiKeySecret
     * @mbg.generated
     */
    public String getApikeysecret() {
        return apikeysecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_key.apiKeySecret
     *
     * @param apikeysecret the value for firm_offer_key.apiKeySecret
     * @mbg.generated
     */
    public void setApikeysecret(String apikeysecret) {
        this.apikeysecret = apikeysecret == null ? null : apikeysecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_key.status
     *
     * @return the value of firm_offer_key.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_key.status
     *
     * @param status the value for firm_offer_key.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_key.passphrase
     *
     * @return the value of firm_offer_key.passphrase
     * @mbg.generated
     */
    public String getPassphrase() {
        return passphrase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_key.passphrase
     *
     * @param passphrase the value for firm_offer_key.passphrase
     * @mbg.generated
     */
    public void setPassphrase(String passphrase) {
        this.passphrase = passphrase == null ? null : passphrase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_key.numberOfDays
     *
     * @return the value of firm_offer_key.numberOfDays
     * @mbg.generated
     */
    public Integer getNumberofdays() {
        return numberofdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_key.numberOfDays
     *
     * @param numberofdays the value for firm_offer_key.numberOfDays
     * @mbg.generated
     */
    public void setNumberofdays(Integer numberofdays) {
        this.numberofdays = numberofdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_key.spider_num
     *
     * @return the value of firm_offer_key.spider_num
     * @mbg.generated
     */
    public Integer getSpiderNum() {
        return spiderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_key.spider_num
     *
     * @param spiderNum the value for firm_offer_key.spider_num
     * @mbg.generated
     */
    public void setSpiderNum(Integer spiderNum) {
        this.spiderNum = spiderNum;
    }
}