package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

public class FirmOfferExchangeBalance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.ex_change
     *
     * @mbg.generated
     */
    private String exChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.available
     *
     * @mbg.generated
     */
    private BigDecimal available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.loan
     *
     * @mbg.generated
     */
    private BigDecimal loan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.freeze
     *
     * @mbg.generated
     */
    private BigDecimal freeze;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.fee
     *
     * @mbg.generated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.coin
     *
     * @mbg.generated
     */
    private Integer coin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_exchange_balance.u_time
     *
     * @mbg.generated
     */
    private Date uTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.id
     *
     * @return the value of firm_offer_exchange_balance.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.id
     *
     * @param id the value for firm_offer_exchange_balance.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.user_id
     *
     * @return the value of firm_offer_exchange_balance.user_id
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.user_id
     *
     * @param userId the value for firm_offer_exchange_balance.user_id
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.ex_change
     *
     * @return the value of firm_offer_exchange_balance.ex_change
     * @mbg.generated
     */
    public String getExChange() {
        return exChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.ex_change
     *
     * @param exChange the value for firm_offer_exchange_balance.ex_change
     * @mbg.generated
     */
    public void setExChange(String exChange) {
        this.exChange = exChange == null ? null : exChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.available
     *
     * @return the value of firm_offer_exchange_balance.available
     * @mbg.generated
     */
    public BigDecimal getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.available
     *
     * @param available the value for firm_offer_exchange_balance.available
     * @mbg.generated
     */
    public void setAvailable(BigDecimal available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.loan
     *
     * @return the value of firm_offer_exchange_balance.loan
     * @mbg.generated
     */
    public BigDecimal getLoan() {
        return loan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.loan
     *
     * @param loan the value for firm_offer_exchange_balance.loan
     * @mbg.generated
     */
    public void setLoan(BigDecimal loan) {
        this.loan = loan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.freeze
     *
     * @return the value of firm_offer_exchange_balance.freeze
     * @mbg.generated
     */
    public BigDecimal getFreeze() {
        return freeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.freeze
     *
     * @param freeze the value for firm_offer_exchange_balance.freeze
     * @mbg.generated
     */
    public void setFreeze(BigDecimal freeze) {
        this.freeze = freeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.fee
     *
     * @return the value of firm_offer_exchange_balance.fee
     * @mbg.generated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.fee
     *
     * @param fee the value for firm_offer_exchange_balance.fee
     * @mbg.generated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.coin
     *
     * @return the value of firm_offer_exchange_balance.coin
     * @mbg.generated
     */
    public Integer getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.coin
     *
     * @param coin the value for firm_offer_exchange_balance.coin
     * @mbg.generated
     */
    public void setCoin(Integer coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.symbol
     *
     * @return the value of firm_offer_exchange_balance.symbol
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.symbol
     *
     * @param symbol the value for firm_offer_exchange_balance.symbol
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.amount
     *
     * @return the value of firm_offer_exchange_balance.amount
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.amount
     *
     * @param amount the value for firm_offer_exchange_balance.amount
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.type
     *
     * @return the value of firm_offer_exchange_balance.type
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.type
     *
     * @param type the value for firm_offer_exchange_balance.type
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_exchange_balance.u_time
     *
     * @return the value of firm_offer_exchange_balance.u_time
     * @mbg.generated
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_exchange_balance.u_time
     *
     * @param uTime the value for firm_offer_exchange_balance.u_time
     * @mbg.generated
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }
}