package com.ailu.firmoffer.dao.bean;

public class FirmOfferCoinContrast {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.full
     *
     * @mbg.generated
     */
    private String full;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.chinese
     *
     * @mbg.generated
     */
    private String chinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.bitfinex_chinese
     *
     * @mbg.generated
     */
    private String bitfinexChinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.bitfinex_symbol
     *
     * @mbg.generated
     */
    private String bitfinexSymbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.bitfinex_full
     *
     * @mbg.generated
     */
    private String bitfinexFull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.huobi_full
     *
     * @mbg.generated
     */
    private String huobiFull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.huobi_symbol
     *
     * @mbg.generated
     */
    private String huobiSymbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.huobi_chinese
     *
     * @mbg.generated
     */
    private String huobiChinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrast.coin
     *
     * @mbg.generated
     */
    private Integer coin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.id
     *
     * @return the value of firm_offer_coin_contrast.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.id
     *
     * @param id the value for firm_offer_coin_contrast.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.symbol
     *
     * @return the value of firm_offer_coin_contrast.symbol
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.symbol
     *
     * @param symbol the value for firm_offer_coin_contrast.symbol
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.full
     *
     * @return the value of firm_offer_coin_contrast.full
     * @mbg.generated
     */
    public String getFull() {
        return full;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.full
     *
     * @param full the value for firm_offer_coin_contrast.full
     * @mbg.generated
     */
    public void setFull(String full) {
        this.full = full == null ? null : full.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.chinese
     *
     * @return the value of firm_offer_coin_contrast.chinese
     * @mbg.generated
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.chinese
     *
     * @param chinese the value for firm_offer_coin_contrast.chinese
     * @mbg.generated
     */
    public void setChinese(String chinese) {
        this.chinese = chinese == null ? null : chinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.bitfinex_chinese
     *
     * @return the value of firm_offer_coin_contrast.bitfinex_chinese
     * @mbg.generated
     */
    public String getBitfinexChinese() {
        return bitfinexChinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.bitfinex_chinese
     *
     * @param bitfinexChinese the value for firm_offer_coin_contrast.bitfinex_chinese
     * @mbg.generated
     */
    public void setBitfinexChinese(String bitfinexChinese) {
        this.bitfinexChinese = bitfinexChinese == null ? null : bitfinexChinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.bitfinex_symbol
     *
     * @return the value of firm_offer_coin_contrast.bitfinex_symbol
     * @mbg.generated
     */
    public String getBitfinexSymbol() {
        return bitfinexSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.bitfinex_symbol
     *
     * @param bitfinexSymbol the value for firm_offer_coin_contrast.bitfinex_symbol
     * @mbg.generated
     */
    public void setBitfinexSymbol(String bitfinexSymbol) {
        this.bitfinexSymbol = bitfinexSymbol == null ? null : bitfinexSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.bitfinex_full
     *
     * @return the value of firm_offer_coin_contrast.bitfinex_full
     * @mbg.generated
     */
    public String getBitfinexFull() {
        return bitfinexFull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.bitfinex_full
     *
     * @param bitfinexFull the value for firm_offer_coin_contrast.bitfinex_full
     * @mbg.generated
     */
    public void setBitfinexFull(String bitfinexFull) {
        this.bitfinexFull = bitfinexFull == null ? null : bitfinexFull.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.huobi_full
     *
     * @return the value of firm_offer_coin_contrast.huobi_full
     * @mbg.generated
     */
    public String getHuobiFull() {
        return huobiFull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.huobi_full
     *
     * @param huobiFull the value for firm_offer_coin_contrast.huobi_full
     * @mbg.generated
     */
    public void setHuobiFull(String huobiFull) {
        this.huobiFull = huobiFull == null ? null : huobiFull.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.huobi_symbol
     *
     * @return the value of firm_offer_coin_contrast.huobi_symbol
     * @mbg.generated
     */
    public String getHuobiSymbol() {
        return huobiSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.huobi_symbol
     *
     * @param huobiSymbol the value for firm_offer_coin_contrast.huobi_symbol
     * @mbg.generated
     */
    public void setHuobiSymbol(String huobiSymbol) {
        this.huobiSymbol = huobiSymbol == null ? null : huobiSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.huobi_chinese
     *
     * @return the value of firm_offer_coin_contrast.huobi_chinese
     * @mbg.generated
     */
    public String getHuobiChinese() {
        return huobiChinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.huobi_chinese
     *
     * @param huobiChinese the value for firm_offer_coin_contrast.huobi_chinese
     * @mbg.generated
     */
    public void setHuobiChinese(String huobiChinese) {
        this.huobiChinese = huobiChinese == null ? null : huobiChinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrast.coin
     *
     * @return the value of firm_offer_coin_contrast.coin
     * @mbg.generated
     */
    public Integer getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrast.coin
     *
     * @param coin the value for firm_offer_coin_contrast.coin
     * @mbg.generated
     */
    public void setCoin(Integer coin) {
        this.coin = coin;
    }
}