package com.ailu.firmoffer.dao.bean;

public class FirmOfferCoinContrasts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrasts.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrasts.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrasts.full
     *
     * @mbg.generated
     */
    private String full;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrasts.chinese
     *
     * @mbg.generated
     */
    private String chinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrasts.coin
     *
     * @mbg.generated
     */
    private Integer coin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrasts.parent
     *
     * @mbg.generated
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_coin_contrasts.ex_change
     *
     * @mbg.generated
     */
    private String exChange;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrasts.id
     *
     * @return the value of firm_offer_coin_contrasts.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrasts.id
     *
     * @param id the value for firm_offer_coin_contrasts.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrasts.symbol
     *
     * @return the value of firm_offer_coin_contrasts.symbol
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrasts.symbol
     *
     * @param symbol the value for firm_offer_coin_contrasts.symbol
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrasts.full
     *
     * @return the value of firm_offer_coin_contrasts.full
     * @mbg.generated
     */
    public String getFull() {
        return full;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrasts.full
     *
     * @param full the value for firm_offer_coin_contrasts.full
     * @mbg.generated
     */
    public void setFull(String full) {
        this.full = full == null ? null : full.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrasts.chinese
     *
     * @return the value of firm_offer_coin_contrasts.chinese
     * @mbg.generated
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrasts.chinese
     *
     * @param chinese the value for firm_offer_coin_contrasts.chinese
     * @mbg.generated
     */
    public void setChinese(String chinese) {
        this.chinese = chinese == null ? null : chinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrasts.coin
     *
     * @return the value of firm_offer_coin_contrasts.coin
     * @mbg.generated
     */
    public Integer getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrasts.coin
     *
     * @param coin the value for firm_offer_coin_contrasts.coin
     * @mbg.generated
     */
    public void setCoin(Integer coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrasts.parent
     *
     * @return the value of firm_offer_coin_contrasts.parent
     * @mbg.generated
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrasts.parent
     *
     * @param parent the value for firm_offer_coin_contrasts.parent
     * @mbg.generated
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_coin_contrasts.ex_change
     *
     * @return the value of firm_offer_coin_contrasts.ex_change
     * @mbg.generated
     */
    public String getExChange() {
        return exChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_coin_contrasts.ex_change
     *
     * @param exChange the value for firm_offer_coin_contrasts.ex_change
     * @mbg.generated
     */
    public void setExChange(String exChange) {
        this.exChange = exChange == null ? null : exChange.trim();
    }
}