package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;

public class FirmOfferTransfer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_transfer.transfer_id
     *
     * @mbg.generated
     */
    private String transferId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_transfer.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_transfer.from
     *
     * @mbg.generated
     */
    private BigDecimal from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_transfer.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_transfer.to
     *
     * @mbg.generated
     */
    private BigDecimal to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column firm_offer_transfer.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_transfer.transfer_id
     *
     * @return the value of firm_offer_transfer.transfer_id
     * @mbg.generated
     */
    public String getTransferId() {
        return transferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_transfer.transfer_id
     *
     * @param transferId the value for firm_offer_transfer.transfer_id
     * @mbg.generated
     */
    public void setTransferId(String transferId) {
        this.transferId = transferId == null ? null : transferId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_transfer.currency
     *
     * @return the value of firm_offer_transfer.currency
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_transfer.currency
     *
     * @param currency the value for firm_offer_transfer.currency
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_transfer.from
     *
     * @return the value of firm_offer_transfer.from
     * @mbg.generated
     */
    public BigDecimal getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_transfer.from
     *
     * @param from the value for firm_offer_transfer.from
     * @mbg.generated
     */
    public void setFrom(BigDecimal from) {
        this.from = from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_transfer.amount
     *
     * @return the value of firm_offer_transfer.amount
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_transfer.amount
     *
     * @param amount the value for firm_offer_transfer.amount
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_transfer.to
     *
     * @return the value of firm_offer_transfer.to
     * @mbg.generated
     */
    public BigDecimal getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_transfer.to
     *
     * @param to the value for firm_offer_transfer.to
     * @mbg.generated
     */
    public void setTo(BigDecimal to) {
        this.to = to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column firm_offer_transfer.result
     *
     * @return the value of firm_offer_transfer.result
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column firm_offer_transfer.result
     *
     * @param result the value for firm_offer_transfer.result
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }
}