package com.ailu.firmoffer.dao.bean;

import java.util.ArrayList;
import java.util.List;

public class FirmOfferCoinContrastExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public FirmOfferCoinContrastExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNull() {
            addCriterion("symbol is null");
            return (Criteria) this;
        }

        public Criteria andSymbolIsNotNull() {
            addCriterion("symbol is not null");
            return (Criteria) this;
        }

        public Criteria andSymbolEqualTo(String value) {
            addCriterion("symbol =", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotEqualTo(String value) {
            addCriterion("symbol <>", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThan(String value) {
            addCriterion("symbol >", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("symbol >=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThan(String value) {
            addCriterion("symbol <", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLessThanOrEqualTo(String value) {
            addCriterion("symbol <=", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolLike(String value) {
            addCriterion("symbol like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotLike(String value) {
            addCriterion("symbol not like", value, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolIn(List<String> values) {
            addCriterion("symbol in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotIn(List<String> values) {
            addCriterion("symbol not in", values, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolBetween(String value1, String value2) {
            addCriterion("symbol between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andSymbolNotBetween(String value1, String value2) {
            addCriterion("symbol not between", value1, value2, "symbol");
            return (Criteria) this;
        }

        public Criteria andFullIsNull() {
            addCriterion("full is null");
            return (Criteria) this;
        }

        public Criteria andFullIsNotNull() {
            addCriterion("full is not null");
            return (Criteria) this;
        }

        public Criteria andFullEqualTo(String value) {
            addCriterion("full =", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullNotEqualTo(String value) {
            addCriterion("full <>", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullGreaterThan(String value) {
            addCriterion("full >", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullGreaterThanOrEqualTo(String value) {
            addCriterion("full >=", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullLessThan(String value) {
            addCriterion("full <", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullLessThanOrEqualTo(String value) {
            addCriterion("full <=", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullLike(String value) {
            addCriterion("full like", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullNotLike(String value) {
            addCriterion("full not like", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullIn(List<String> values) {
            addCriterion("full in", values, "full");
            return (Criteria) this;
        }

        public Criteria andFullNotIn(List<String> values) {
            addCriterion("full not in", values, "full");
            return (Criteria) this;
        }

        public Criteria andFullBetween(String value1, String value2) {
            addCriterion("full between", value1, value2, "full");
            return (Criteria) this;
        }

        public Criteria andFullNotBetween(String value1, String value2) {
            addCriterion("full not between", value1, value2, "full");
            return (Criteria) this;
        }

        public Criteria andChineseIsNull() {
            addCriterion("chinese is null");
            return (Criteria) this;
        }

        public Criteria andChineseIsNotNull() {
            addCriterion("chinese is not null");
            return (Criteria) this;
        }

        public Criteria andChineseEqualTo(String value) {
            addCriterion("chinese =", value, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseNotEqualTo(String value) {
            addCriterion("chinese <>", value, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseGreaterThan(String value) {
            addCriterion("chinese >", value, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseGreaterThanOrEqualTo(String value) {
            addCriterion("chinese >=", value, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseLessThan(String value) {
            addCriterion("chinese <", value, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseLessThanOrEqualTo(String value) {
            addCriterion("chinese <=", value, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseLike(String value) {
            addCriterion("chinese like", value, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseNotLike(String value) {
            addCriterion("chinese not like", value, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseIn(List<String> values) {
            addCriterion("chinese in", values, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseNotIn(List<String> values) {
            addCriterion("chinese not in", values, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseBetween(String value1, String value2) {
            addCriterion("chinese between", value1, value2, "chinese");
            return (Criteria) this;
        }

        public Criteria andChineseNotBetween(String value1, String value2) {
            addCriterion("chinese not between", value1, value2, "chinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseIsNull() {
            addCriterion("bitfinex_chinese is null");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseIsNotNull() {
            addCriterion("bitfinex_chinese is not null");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseEqualTo(String value) {
            addCriterion("bitfinex_chinese =", value, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseNotEqualTo(String value) {
            addCriterion("bitfinex_chinese <>", value, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseGreaterThan(String value) {
            addCriterion("bitfinex_chinese >", value, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseGreaterThanOrEqualTo(String value) {
            addCriterion("bitfinex_chinese >=", value, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseLessThan(String value) {
            addCriterion("bitfinex_chinese <", value, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseLessThanOrEqualTo(String value) {
            addCriterion("bitfinex_chinese <=", value, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseLike(String value) {
            addCriterion("bitfinex_chinese like", value, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseNotLike(String value) {
            addCriterion("bitfinex_chinese not like", value, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseIn(List<String> values) {
            addCriterion("bitfinex_chinese in", values, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseNotIn(List<String> values) {
            addCriterion("bitfinex_chinese not in", values, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseBetween(String value1, String value2) {
            addCriterion("bitfinex_chinese between", value1, value2, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexChineseNotBetween(String value1, String value2) {
            addCriterion("bitfinex_chinese not between", value1, value2, "bitfinexChinese");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolIsNull() {
            addCriterion("bitfinex_symbol is null");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolIsNotNull() {
            addCriterion("bitfinex_symbol is not null");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolEqualTo(String value) {
            addCriterion("bitfinex_symbol =", value, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolNotEqualTo(String value) {
            addCriterion("bitfinex_symbol <>", value, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolGreaterThan(String value) {
            addCriterion("bitfinex_symbol >", value, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("bitfinex_symbol >=", value, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolLessThan(String value) {
            addCriterion("bitfinex_symbol <", value, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolLessThanOrEqualTo(String value) {
            addCriterion("bitfinex_symbol <=", value, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolLike(String value) {
            addCriterion("bitfinex_symbol like", value, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolNotLike(String value) {
            addCriterion("bitfinex_symbol not like", value, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolIn(List<String> values) {
            addCriterion("bitfinex_symbol in", values, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolNotIn(List<String> values) {
            addCriterion("bitfinex_symbol not in", values, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolBetween(String value1, String value2) {
            addCriterion("bitfinex_symbol between", value1, value2, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexSymbolNotBetween(String value1, String value2) {
            addCriterion("bitfinex_symbol not between", value1, value2, "bitfinexSymbol");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullIsNull() {
            addCriterion("bitfinex_full is null");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullIsNotNull() {
            addCriterion("bitfinex_full is not null");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullEqualTo(String value) {
            addCriterion("bitfinex_full =", value, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullNotEqualTo(String value) {
            addCriterion("bitfinex_full <>", value, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullGreaterThan(String value) {
            addCriterion("bitfinex_full >", value, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullGreaterThanOrEqualTo(String value) {
            addCriterion("bitfinex_full >=", value, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullLessThan(String value) {
            addCriterion("bitfinex_full <", value, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullLessThanOrEqualTo(String value) {
            addCriterion("bitfinex_full <=", value, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullLike(String value) {
            addCriterion("bitfinex_full like", value, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullNotLike(String value) {
            addCriterion("bitfinex_full not like", value, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullIn(List<String> values) {
            addCriterion("bitfinex_full in", values, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullNotIn(List<String> values) {
            addCriterion("bitfinex_full not in", values, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullBetween(String value1, String value2) {
            addCriterion("bitfinex_full between", value1, value2, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andBitfinexFullNotBetween(String value1, String value2) {
            addCriterion("bitfinex_full not between", value1, value2, "bitfinexFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullIsNull() {
            addCriterion("huobi_full is null");
            return (Criteria) this;
        }

        public Criteria andHuobiFullIsNotNull() {
            addCriterion("huobi_full is not null");
            return (Criteria) this;
        }

        public Criteria andHuobiFullEqualTo(String value) {
            addCriterion("huobi_full =", value, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullNotEqualTo(String value) {
            addCriterion("huobi_full <>", value, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullGreaterThan(String value) {
            addCriterion("huobi_full >", value, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullGreaterThanOrEqualTo(String value) {
            addCriterion("huobi_full >=", value, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullLessThan(String value) {
            addCriterion("huobi_full <", value, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullLessThanOrEqualTo(String value) {
            addCriterion("huobi_full <=", value, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullLike(String value) {
            addCriterion("huobi_full like", value, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullNotLike(String value) {
            addCriterion("huobi_full not like", value, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullIn(List<String> values) {
            addCriterion("huobi_full in", values, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullNotIn(List<String> values) {
            addCriterion("huobi_full not in", values, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullBetween(String value1, String value2) {
            addCriterion("huobi_full between", value1, value2, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiFullNotBetween(String value1, String value2) {
            addCriterion("huobi_full not between", value1, value2, "huobiFull");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolIsNull() {
            addCriterion("huobi_symbol is null");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolIsNotNull() {
            addCriterion("huobi_symbol is not null");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolEqualTo(String value) {
            addCriterion("huobi_symbol =", value, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolNotEqualTo(String value) {
            addCriterion("huobi_symbol <>", value, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolGreaterThan(String value) {
            addCriterion("huobi_symbol >", value, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("huobi_symbol >=", value, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolLessThan(String value) {
            addCriterion("huobi_symbol <", value, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolLessThanOrEqualTo(String value) {
            addCriterion("huobi_symbol <=", value, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolLike(String value) {
            addCriterion("huobi_symbol like", value, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolNotLike(String value) {
            addCriterion("huobi_symbol not like", value, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolIn(List<String> values) {
            addCriterion("huobi_symbol in", values, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolNotIn(List<String> values) {
            addCriterion("huobi_symbol not in", values, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolBetween(String value1, String value2) {
            addCriterion("huobi_symbol between", value1, value2, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiSymbolNotBetween(String value1, String value2) {
            addCriterion("huobi_symbol not between", value1, value2, "huobiSymbol");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseIsNull() {
            addCriterion("huobi_chinese is null");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseIsNotNull() {
            addCriterion("huobi_chinese is not null");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseEqualTo(String value) {
            addCriterion("huobi_chinese =", value, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseNotEqualTo(String value) {
            addCriterion("huobi_chinese <>", value, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseGreaterThan(String value) {
            addCriterion("huobi_chinese >", value, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseGreaterThanOrEqualTo(String value) {
            addCriterion("huobi_chinese >=", value, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseLessThan(String value) {
            addCriterion("huobi_chinese <", value, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseLessThanOrEqualTo(String value) {
            addCriterion("huobi_chinese <=", value, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseLike(String value) {
            addCriterion("huobi_chinese like", value, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseNotLike(String value) {
            addCriterion("huobi_chinese not like", value, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseIn(List<String> values) {
            addCriterion("huobi_chinese in", values, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseNotIn(List<String> values) {
            addCriterion("huobi_chinese not in", values, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseBetween(String value1, String value2) {
            addCriterion("huobi_chinese between", value1, value2, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andHuobiChineseNotBetween(String value1, String value2) {
            addCriterion("huobi_chinese not between", value1, value2, "huobiChinese");
            return (Criteria) this;
        }

        public Criteria andCoinIsNull() {
            addCriterion("coin is null");
            return (Criteria) this;
        }

        public Criteria andCoinIsNotNull() {
            addCriterion("coin is not null");
            return (Criteria) this;
        }

        public Criteria andCoinEqualTo(Integer value) {
            addCriterion("coin =", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinNotEqualTo(Integer value) {
            addCriterion("coin <>", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinGreaterThan(Integer value) {
            addCriterion("coin >", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("coin >=", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinLessThan(Integer value) {
            addCriterion("coin <", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinLessThanOrEqualTo(Integer value) {
            addCriterion("coin <=", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinIn(List<Integer> values) {
            addCriterion("coin in", values, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinNotIn(List<Integer> values) {
            addCriterion("coin not in", values, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinBetween(Integer value1, Integer value2) {
            addCriterion("coin between", value1, value2, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinNotBetween(Integer value1, Integer value2) {
            addCriterion("coin not between", value1, value2, "coin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}