package com.ailu.firmoffer.dao.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FirmOfferPositionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public FirmOfferPositionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andExChangeIsNull() {
            addCriterion("ex_change is null");
            return (Criteria) this;
        }

        public Criteria andExChangeIsNotNull() {
            addCriterion("ex_change is not null");
            return (Criteria) this;
        }

        public Criteria andExChangeEqualTo(String value) {
            addCriterion("ex_change =", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotEqualTo(String value) {
            addCriterion("ex_change <>", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeGreaterThan(String value) {
            addCriterion("ex_change >", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeGreaterThanOrEqualTo(String value) {
            addCriterion("ex_change >=", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeLessThan(String value) {
            addCriterion("ex_change <", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeLessThanOrEqualTo(String value) {
            addCriterion("ex_change <=", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeLike(String value) {
            addCriterion("ex_change like", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotLike(String value) {
            addCriterion("ex_change not like", value, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeIn(List<String> values) {
            addCriterion("ex_change in", values, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotIn(List<String> values) {
            addCriterion("ex_change not in", values, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeBetween(String value1, String value2) {
            addCriterion("ex_change between", value1, value2, "exChange");
            return (Criteria) this;
        }

        public Criteria andExChangeNotBetween(String value1, String value2) {
            addCriterion("ex_change not between", value1, value2, "exChange");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdIsNull() {
            addCriterion("instrument_id is null");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdIsNotNull() {
            addCriterion("instrument_id is not null");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdEqualTo(String value) {
            addCriterion("instrument_id =", value, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdNotEqualTo(String value) {
            addCriterion("instrument_id <>", value, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdGreaterThan(String value) {
            addCriterion("instrument_id >", value, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdGreaterThanOrEqualTo(String value) {
            addCriterion("instrument_id >=", value, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdLessThan(String value) {
            addCriterion("instrument_id <", value, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdLessThanOrEqualTo(String value) {
            addCriterion("instrument_id <=", value, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdLike(String value) {
            addCriterion("instrument_id like", value, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdNotLike(String value) {
            addCriterion("instrument_id not like", value, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdIn(List<String> values) {
            addCriterion("instrument_id in", values, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdNotIn(List<String> values) {
            addCriterion("instrument_id not in", values, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdBetween(String value1, String value2) {
            addCriterion("instrument_id between", value1, value2, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andInstrumentIdNotBetween(String value1, String value2) {
            addCriterion("instrument_id not between", value1, value2, "instrumentId");
            return (Criteria) this;
        }

        public Criteria andTradingOnIsNull() {
            addCriterion("trading_on is null");
            return (Criteria) this;
        }

        public Criteria andTradingOnIsNotNull() {
            addCriterion("trading_on is not null");
            return (Criteria) this;
        }

        public Criteria andTradingOnEqualTo(String value) {
            addCriterion("trading_on =", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnNotEqualTo(String value) {
            addCriterion("trading_on <>", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnGreaterThan(String value) {
            addCriterion("trading_on >", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnGreaterThanOrEqualTo(String value) {
            addCriterion("trading_on >=", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnLessThan(String value) {
            addCriterion("trading_on <", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnLessThanOrEqualTo(String value) {
            addCriterion("trading_on <=", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnLike(String value) {
            addCriterion("trading_on like", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnNotLike(String value) {
            addCriterion("trading_on not like", value, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnIn(List<String> values) {
            addCriterion("trading_on in", values, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnNotIn(List<String> values) {
            addCriterion("trading_on not in", values, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnBetween(String value1, String value2) {
            addCriterion("trading_on between", value1, value2, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTradingOnNotBetween(String value1, String value2) {
            addCriterion("trading_on not between", value1, value2, "tradingOn");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andMarginModeIsNull() {
            addCriterion("margin_mode is null");
            return (Criteria) this;
        }

        public Criteria andMarginModeIsNotNull() {
            addCriterion("margin_mode is not null");
            return (Criteria) this;
        }

        public Criteria andMarginModeEqualTo(String value) {
            addCriterion("margin_mode =", value, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeNotEqualTo(String value) {
            addCriterion("margin_mode <>", value, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeGreaterThan(String value) {
            addCriterion("margin_mode >", value, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeGreaterThanOrEqualTo(String value) {
            addCriterion("margin_mode >=", value, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeLessThan(String value) {
            addCriterion("margin_mode <", value, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeLessThanOrEqualTo(String value) {
            addCriterion("margin_mode <=", value, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeLike(String value) {
            addCriterion("margin_mode like", value, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeNotLike(String value) {
            addCriterion("margin_mode not like", value, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeIn(List<String> values) {
            addCriterion("margin_mode in", values, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeNotIn(List<String> values) {
            addCriterion("margin_mode not in", values, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeBetween(String value1, String value2) {
            addCriterion("margin_mode between", value1, value2, "marginMode");
            return (Criteria) this;
        }

        public Criteria andMarginModeNotBetween(String value1, String value2) {
            addCriterion("margin_mode not between", value1, value2, "marginMode");
            return (Criteria) this;
        }

        public Criteria andPositionDateIsNull() {
            addCriterion("position_date is null");
            return (Criteria) this;
        }

        public Criteria andPositionDateIsNotNull() {
            addCriterion("position_date is not null");
            return (Criteria) this;
        }

        public Criteria andPositionDateEqualTo(Date value) {
            addCriterion("position_date =", value, "positionDate");
            return (Criteria) this;
        }

        public Criteria andPositionDateNotEqualTo(Date value) {
            addCriterion("position_date <>", value, "positionDate");
            return (Criteria) this;
        }

        public Criteria andPositionDateGreaterThan(Date value) {
            addCriterion("position_date >", value, "positionDate");
            return (Criteria) this;
        }

        public Criteria andPositionDateGreaterThanOrEqualTo(Date value) {
            addCriterion("position_date >=", value, "positionDate");
            return (Criteria) this;
        }

        public Criteria andPositionDateLessThan(Date value) {
            addCriterion("position_date <", value, "positionDate");
            return (Criteria) this;
        }

        public Criteria andPositionDateLessThanOrEqualTo(Date value) {
            addCriterion("position_date <=", value, "positionDate");
            return (Criteria) this;
        }

        public Criteria andPositionDateIn(List<Date> values) {
            addCriterion("position_date in", values, "positionDate");
            return (Criteria) this;
        }

        public Criteria andPositionDateNotIn(List<Date> values) {
            addCriterion("position_date not in", values, "positionDate");
            return (Criteria) this;
        }

        public Criteria andPositionDateBetween(Date value1, Date value2) {
            addCriterion("position_date between", value1, value2, "positionDate");
            return (Criteria) this;
        }

        public Criteria andPositionDateNotBetween(Date value1, Date value2) {
            addCriterion("position_date not between", value1, value2, "positionDate");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceIsNull() {
            addCriterion("liquidation_price is null");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceIsNotNull() {
            addCriterion("liquidation_price is not null");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceEqualTo(BigDecimal value) {
            addCriterion("liquidation_price =", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceNotEqualTo(BigDecimal value) {
            addCriterion("liquidation_price <>", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceGreaterThan(BigDecimal value) {
            addCriterion("liquidation_price >", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("liquidation_price >=", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceLessThan(BigDecimal value) {
            addCriterion("liquidation_price <", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("liquidation_price <=", value, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceIn(List<BigDecimal> values) {
            addCriterion("liquidation_price in", values, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceNotIn(List<BigDecimal> values) {
            addCriterion("liquidation_price not in", values, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("liquidation_price between", value1, value2, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andLiquidationPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("liquidation_price not between", value1, value2, "liquidationPrice");
            return (Criteria) this;
        }

        public Criteria andQtyIsNull() {
            addCriterion("qty is null");
            return (Criteria) this;
        }

        public Criteria andQtyIsNotNull() {
            addCriterion("qty is not null");
            return (Criteria) this;
        }

        public Criteria andQtyEqualTo(BigDecimal value) {
            addCriterion("qty =", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotEqualTo(BigDecimal value) {
            addCriterion("qty <>", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThan(BigDecimal value) {
            addCriterion("qty >", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("qty >=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThan(BigDecimal value) {
            addCriterion("qty <", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("qty <=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyIn(List<BigDecimal> values) {
            addCriterion("qty in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotIn(List<BigDecimal> values) {
            addCriterion("qty not in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("qty between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("qty not between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andAvailQtyIsNull() {
            addCriterion("avail_qty is null");
            return (Criteria) this;
        }

        public Criteria andAvailQtyIsNotNull() {
            addCriterion("avail_qty is not null");
            return (Criteria) this;
        }

        public Criteria andAvailQtyEqualTo(BigDecimal value) {
            addCriterion("avail_qty =", value, "availQty");
            return (Criteria) this;
        }

        public Criteria andAvailQtyNotEqualTo(BigDecimal value) {
            addCriterion("avail_qty <>", value, "availQty");
            return (Criteria) this;
        }

        public Criteria andAvailQtyGreaterThan(BigDecimal value) {
            addCriterion("avail_qty >", value, "availQty");
            return (Criteria) this;
        }

        public Criteria andAvailQtyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("avail_qty >=", value, "availQty");
            return (Criteria) this;
        }

        public Criteria andAvailQtyLessThan(BigDecimal value) {
            addCriterion("avail_qty <", value, "availQty");
            return (Criteria) this;
        }

        public Criteria andAvailQtyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("avail_qty <=", value, "availQty");
            return (Criteria) this;
        }

        public Criteria andAvailQtyIn(List<BigDecimal> values) {
            addCriterion("avail_qty in", values, "availQty");
            return (Criteria) this;
        }

        public Criteria andAvailQtyNotIn(List<BigDecimal> values) {
            addCriterion("avail_qty not in", values, "availQty");
            return (Criteria) this;
        }

        public Criteria andAvailQtyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avail_qty between", value1, value2, "availQty");
            return (Criteria) this;
        }

        public Criteria andAvailQtyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avail_qty not between", value1, value2, "availQty");
            return (Criteria) this;
        }

        public Criteria andAvgCostIsNull() {
            addCriterion("avg_cost is null");
            return (Criteria) this;
        }

        public Criteria andAvgCostIsNotNull() {
            addCriterion("avg_cost is not null");
            return (Criteria) this;
        }

        public Criteria andAvgCostEqualTo(BigDecimal value) {
            addCriterion("avg_cost =", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostNotEqualTo(BigDecimal value) {
            addCriterion("avg_cost <>", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostGreaterThan(BigDecimal value) {
            addCriterion("avg_cost >", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_cost >=", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostLessThan(BigDecimal value) {
            addCriterion("avg_cost <", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_cost <=", value, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostIn(List<BigDecimal> values) {
            addCriterion("avg_cost in", values, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostNotIn(List<BigDecimal> values) {
            addCriterion("avg_cost not in", values, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_cost between", value1, value2, "avgCost");
            return (Criteria) this;
        }

        public Criteria andAvgCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_cost not between", value1, value2, "avgCost");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceIsNull() {
            addCriterion("settlement_price is null");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceIsNotNull() {
            addCriterion("settlement_price is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceEqualTo(BigDecimal value) {
            addCriterion("settlement_price =", value, "settlementPrice");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceNotEqualTo(BigDecimal value) {
            addCriterion("settlement_price <>", value, "settlementPrice");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceGreaterThan(BigDecimal value) {
            addCriterion("settlement_price >", value, "settlementPrice");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("settlement_price >=", value, "settlementPrice");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceLessThan(BigDecimal value) {
            addCriterion("settlement_price <", value, "settlementPrice");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("settlement_price <=", value, "settlementPrice");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceIn(List<BigDecimal> values) {
            addCriterion("settlement_price in", values, "settlementPrice");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceNotIn(List<BigDecimal> values) {
            addCriterion("settlement_price not in", values, "settlementPrice");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("settlement_price between", value1, value2, "settlementPrice");
            return (Criteria) this;
        }

        public Criteria andSettlementPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("settlement_price not between", value1, value2, "settlementPrice");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceIsNull() {
            addCriterion("liqui_price is null");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceIsNotNull() {
            addCriterion("liqui_price is not null");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceEqualTo(BigDecimal value) {
            addCriterion("liqui_price =", value, "liquiPrice");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceNotEqualTo(BigDecimal value) {
            addCriterion("liqui_price <>", value, "liquiPrice");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceGreaterThan(BigDecimal value) {
            addCriterion("liqui_price >", value, "liquiPrice");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("liqui_price >=", value, "liquiPrice");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceLessThan(BigDecimal value) {
            addCriterion("liqui_price <", value, "liquiPrice");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("liqui_price <=", value, "liquiPrice");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceIn(List<BigDecimal> values) {
            addCriterion("liqui_price in", values, "liquiPrice");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceNotIn(List<BigDecimal> values) {
            addCriterion("liqui_price not in", values, "liquiPrice");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("liqui_price between", value1, value2, "liquiPrice");
            return (Criteria) this;
        }

        public Criteria andLiquiPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("liqui_price not between", value1, value2, "liquiPrice");
            return (Criteria) this;
        }

        public Criteria andPnlRatioIsNull() {
            addCriterion("pnl_ratio is null");
            return (Criteria) this;
        }

        public Criteria andPnlRatioIsNotNull() {
            addCriterion("pnl_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andPnlRatioEqualTo(BigDecimal value) {
            addCriterion("pnl_ratio =", value, "pnlRatio");
            return (Criteria) this;
        }

        public Criteria andPnlRatioNotEqualTo(BigDecimal value) {
            addCriterion("pnl_ratio <>", value, "pnlRatio");
            return (Criteria) this;
        }

        public Criteria andPnlRatioGreaterThan(BigDecimal value) {
            addCriterion("pnl_ratio >", value, "pnlRatio");
            return (Criteria) this;
        }

        public Criteria andPnlRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pnl_ratio >=", value, "pnlRatio");
            return (Criteria) this;
        }

        public Criteria andPnlRatioLessThan(BigDecimal value) {
            addCriterion("pnl_ratio <", value, "pnlRatio");
            return (Criteria) this;
        }

        public Criteria andPnlRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pnl_ratio <=", value, "pnlRatio");
            return (Criteria) this;
        }

        public Criteria andPnlRatioIn(List<BigDecimal> values) {
            addCriterion("pnl_ratio in", values, "pnlRatio");
            return (Criteria) this;
        }

        public Criteria andPnlRatioNotIn(List<BigDecimal> values) {
            addCriterion("pnl_ratio not in", values, "pnlRatio");
            return (Criteria) this;
        }

        public Criteria andPnlRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pnl_ratio between", value1, value2, "pnlRatio");
            return (Criteria) this;
        }

        public Criteria andPnlRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pnl_ratio not between", value1, value2, "pnlRatio");
            return (Criteria) this;
        }

        public Criteria andMarginIsNull() {
            addCriterion("margin is null");
            return (Criteria) this;
        }

        public Criteria andMarginIsNotNull() {
            addCriterion("margin is not null");
            return (Criteria) this;
        }

        public Criteria andMarginEqualTo(BigDecimal value) {
            addCriterion("margin =", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginNotEqualTo(BigDecimal value) {
            addCriterion("margin <>", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginGreaterThan(BigDecimal value) {
            addCriterion("margin >", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("margin >=", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginLessThan(BigDecimal value) {
            addCriterion("margin <", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginLessThanOrEqualTo(BigDecimal value) {
            addCriterion("margin <=", value, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginIn(List<BigDecimal> values) {
            addCriterion("margin in", values, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginNotIn(List<BigDecimal> values) {
            addCriterion("margin not in", values, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("margin between", value1, value2, "margin");
            return (Criteria) this;
        }

        public Criteria andMarginNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("margin not between", value1, value2, "margin");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlIsNull() {
            addCriterion("realized_pnl is null");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlIsNotNull() {
            addCriterion("realized_pnl is not null");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlEqualTo(BigDecimal value) {
            addCriterion("realized_pnl =", value, "realizedPnl");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlNotEqualTo(BigDecimal value) {
            addCriterion("realized_pnl <>", value, "realizedPnl");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlGreaterThan(BigDecimal value) {
            addCriterion("realized_pnl >", value, "realizedPnl");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("realized_pnl >=", value, "realizedPnl");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlLessThan(BigDecimal value) {
            addCriterion("realized_pnl <", value, "realizedPnl");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("realized_pnl <=", value, "realizedPnl");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlIn(List<BigDecimal> values) {
            addCriterion("realized_pnl in", values, "realizedPnl");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlNotIn(List<BigDecimal> values) {
            addCriterion("realized_pnl not in", values, "realizedPnl");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("realized_pnl between", value1, value2, "realizedPnl");
            return (Criteria) this;
        }

        public Criteria andRealizedPnlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("realized_pnl not between", value1, value2, "realizedPnl");
            return (Criteria) this;
        }

        public Criteria andLeverageIsNull() {
            addCriterion("leverage is null");
            return (Criteria) this;
        }

        public Criteria andLeverageIsNotNull() {
            addCriterion("leverage is not null");
            return (Criteria) this;
        }

        public Criteria andLeverageEqualTo(String value) {
            addCriterion("leverage =", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageNotEqualTo(String value) {
            addCriterion("leverage <>", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageGreaterThan(String value) {
            addCriterion("leverage >", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageGreaterThanOrEqualTo(String value) {
            addCriterion("leverage >=", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageLessThan(String value) {
            addCriterion("leverage <", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageLessThanOrEqualTo(String value) {
            addCriterion("leverage <=", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageLike(String value) {
            addCriterion("leverage like", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageNotLike(String value) {
            addCriterion("leverage not like", value, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageIn(List<String> values) {
            addCriterion("leverage in", values, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageNotIn(List<String> values) {
            addCriterion("leverage not in", values, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageBetween(String value1, String value2) {
            addCriterion("leverage between", value1, value2, "leverage");
            return (Criteria) this;
        }

        public Criteria andLeverageNotBetween(String value1, String value2) {
            addCriterion("leverage not between", value1, value2, "leverage");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNull() {
            addCriterion("utime is null");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNotNull() {
            addCriterion("utime is not null");
            return (Criteria) this;
        }

        public Criteria andUtimeEqualTo(Date value) {
            addCriterion("utime =", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotEqualTo(Date value) {
            addCriterion("utime <>", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThan(Date value) {
            addCriterion("utime >", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("utime >=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThan(Date value) {
            addCriterion("utime <", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThanOrEqualTo(Date value) {
            addCriterion("utime <=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeIn(List<Date> values) {
            addCriterion("utime in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotIn(List<Date> values) {
            addCriterion("utime not in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeBetween(Date value1, Date value2) {
            addCriterion("utime between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotBetween(Date value1, Date value2) {
            addCriterion("utime not between", value1, value2, "utime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_position
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table firm_offer_position
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}