package com.ailu.firmoffer.dao.bean;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.im_token
     *
     * @mbg.generated
     */
    private String imToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bigV
     *
     * @mbg.generated
     */
    private Integer bigv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.subscribe_charge
     *
     * @mbg.generated
     */
    private Integer subscribeCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.brief
     *
     * @mbg.generated
     */
    private String brief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.v_brief
     *
     * @mbg.generated
     */
    private String vBrief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.play_game
     *
     * @mbg.generated
     */
    private Integer playGame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gold_coin
     *
     * @mbg.generated
     */
    private Integer goldCoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.invite_code
     *
     * @mbg.generated
     */
    private String inviteCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.im_token
     *
     * @return the value of user.im_token
     * @mbg.generated
     */
    public String getImToken() {
        return imToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.im_token
     *
     * @param imToken the value for user.im_token
     * @mbg.generated
     */
    public void setImToken(String imToken) {
        this.imToken = imToken == null ? null : imToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bigV
     *
     * @return the value of user.bigV
     * @mbg.generated
     */
    public Integer getBigv() {
        return bigv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bigV
     *
     * @param bigv the value for user.bigV
     * @mbg.generated
     */
    public void setBigv(Integer bigv) {
        this.bigv = bigv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.subscribe_charge
     *
     * @return the value of user.subscribe_charge
     * @mbg.generated
     */
    public Integer getSubscribeCharge() {
        return subscribeCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.subscribe_charge
     *
     * @param subscribeCharge the value for user.subscribe_charge
     * @mbg.generated
     */
    public void setSubscribeCharge(Integer subscribeCharge) {
        this.subscribeCharge = subscribeCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_time
     *
     * @return the value of user.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_time
     *
     * @param updateTime the value for user.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.score
     *
     * @return the value of user.score
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.score
     *
     * @param score the value for user.score
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.brief
     *
     * @return the value of user.brief
     * @mbg.generated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.brief
     *
     * @param brief the value for user.brief
     * @mbg.generated
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.v_brief
     *
     * @return the value of user.v_brief
     * @mbg.generated
     */
    public String getvBrief() {
        return vBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.v_brief
     *
     * @param vBrief the value for user.v_brief
     * @mbg.generated
     */
    public void setvBrief(String vBrief) {
        this.vBrief = vBrief == null ? null : vBrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.play_game
     *
     * @return the value of user.play_game
     * @mbg.generated
     */
    public Integer getPlayGame() {
        return playGame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.play_game
     *
     * @param playGame the value for user.play_game
     * @mbg.generated
     */
    public void setPlayGame(Integer playGame) {
        this.playGame = playGame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gold_coin
     *
     * @return the value of user.gold_coin
     * @mbg.generated
     */
    public Integer getGoldCoin() {
        return goldCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gold_coin
     *
     * @param goldCoin the value for user.gold_coin
     * @mbg.generated
     */
    public void setGoldCoin(Integer goldCoin) {
        this.goldCoin = goldCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.invite_code
     *
     * @return the value of user.invite_code
     * @mbg.generated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.invite_code
     *
     * @param inviteCode the value for user.invite_code
     * @mbg.generated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }
}