package com.ailu.firmoffer.dao.bean;

import java.util.Date;

public class UserFirmOffer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.im_token
     *
     * @mbg.generated
     */
    private String imToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.bigV
     *
     * @mbg.generated
     */
    private Integer bigv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.subscribe_charge
     *
     * @mbg.generated
     */
    private Integer subscribeCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.brief
     *
     * @mbg.generated
     */
    private String brief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.v_brief
     *
     * @mbg.generated
     */
    private String vBrief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.play_game
     *
     * @mbg.generated
     */
    private Integer playGame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.gold_coin
     *
     * @mbg.generated
     */
    private Integer goldCoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.invite_code
     *
     * @mbg.generated
     */
    private String inviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.openId
     *
     * @mbg.generated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.hasCoins
     *
     * @mbg.generated
     */
    private String hascoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.show_history
     *
     * @mbg.generated
     */
    private Integer showHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_firm_offer.slogen
     *
     * @mbg.generated
     */
    private String slogen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.id
     *
     * @return the value of user_firm_offer.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.id
     *
     * @param id the value for user_firm_offer.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.nick_name
     *
     * @return the value of user_firm_offer.nick_name
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.nick_name
     *
     * @param nickName the value for user_firm_offer.nick_name
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.password
     *
     * @return the value of user_firm_offer.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.password
     *
     * @param password the value for user_firm_offer.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.email
     *
     * @return the value of user_firm_offer.email
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.email
     *
     * @param email the value for user_firm_offer.email
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.phone
     *
     * @return the value of user_firm_offer.phone
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.phone
     *
     * @param phone the value for user_firm_offer.phone
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.avatar
     *
     * @return the value of user_firm_offer.avatar
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.avatar
     *
     * @param avatar the value for user_firm_offer.avatar
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.im_token
     *
     * @return the value of user_firm_offer.im_token
     * @mbg.generated
     */
    public String getImToken() {
        return imToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.im_token
     *
     * @param imToken the value for user_firm_offer.im_token
     * @mbg.generated
     */
    public void setImToken(String imToken) {
        this.imToken = imToken == null ? null : imToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.bigV
     *
     * @return the value of user_firm_offer.bigV
     * @mbg.generated
     */
    public Integer getBigv() {
        return bigv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.bigV
     *
     * @param bigv the value for user_firm_offer.bigV
     * @mbg.generated
     */
    public void setBigv(Integer bigv) {
        this.bigv = bigv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.subscribe_charge
     *
     * @return the value of user_firm_offer.subscribe_charge
     * @mbg.generated
     */
    public Integer getSubscribeCharge() {
        return subscribeCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.subscribe_charge
     *
     * @param subscribeCharge the value for user_firm_offer.subscribe_charge
     * @mbg.generated
     */
    public void setSubscribeCharge(Integer subscribeCharge) {
        this.subscribeCharge = subscribeCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.create_time
     *
     * @return the value of user_firm_offer.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.create_time
     *
     * @param createTime the value for user_firm_offer.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.update_time
     *
     * @return the value of user_firm_offer.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.update_time
     *
     * @param updateTime the value for user_firm_offer.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.score
     *
     * @return the value of user_firm_offer.score
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.score
     *
     * @param score the value for user_firm_offer.score
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.brief
     *
     * @return the value of user_firm_offer.brief
     * @mbg.generated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.brief
     *
     * @param brief the value for user_firm_offer.brief
     * @mbg.generated
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.v_brief
     *
     * @return the value of user_firm_offer.v_brief
     * @mbg.generated
     */
    public String getvBrief() {
        return vBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.v_brief
     *
     * @param vBrief the value for user_firm_offer.v_brief
     * @mbg.generated
     */
    public void setvBrief(String vBrief) {
        this.vBrief = vBrief == null ? null : vBrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.play_game
     *
     * @return the value of user_firm_offer.play_game
     * @mbg.generated
     */
    public Integer getPlayGame() {
        return playGame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.play_game
     *
     * @param playGame the value for user_firm_offer.play_game
     * @mbg.generated
     */
    public void setPlayGame(Integer playGame) {
        this.playGame = playGame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.gold_coin
     *
     * @return the value of user_firm_offer.gold_coin
     * @mbg.generated
     */
    public Integer getGoldCoin() {
        return goldCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.gold_coin
     *
     * @param goldCoin the value for user_firm_offer.gold_coin
     * @mbg.generated
     */
    public void setGoldCoin(Integer goldCoin) {
        this.goldCoin = goldCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.invite_code
     *
     * @return the value of user_firm_offer.invite_code
     * @mbg.generated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.invite_code
     *
     * @param inviteCode the value for user_firm_offer.invite_code
     * @mbg.generated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode == null ? null : inviteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.openId
     *
     * @return the value of user_firm_offer.openId
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.openId
     *
     * @param openid the value for user_firm_offer.openId
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.hasCoins
     *
     * @return the value of user_firm_offer.hasCoins
     * @mbg.generated
     */
    public String getHascoins() {
        return hascoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.hasCoins
     *
     * @param hascoins the value for user_firm_offer.hasCoins
     * @mbg.generated
     */
    public void setHascoins(String hascoins) {
        this.hascoins = hascoins == null ? null : hascoins.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.show_history
     *
     * @return the value of user_firm_offer.show_history
     * @mbg.generated
     */
    public Integer getShowHistory() {
        return showHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.show_history
     *
     * @param showHistory the value for user_firm_offer.show_history
     * @mbg.generated
     */
    public void setShowHistory(Integer showHistory) {
        this.showHistory = showHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_firm_offer.slogen
     *
     * @return the value of user_firm_offer.slogen
     * @mbg.generated
     */
    public String getSlogen() {
        return slogen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_firm_offer.slogen
     *
     * @param slogen the value for user_firm_offer.slogen
     * @mbg.generated
     */
    public void setSlogen(String slogen) {
        this.slogen = slogen == null ? null : slogen.trim();
    }
}