package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferCoinContrasts;
import com.ailu.firmoffer.dao.bean.FirmOfferCoinContrastsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FirmOfferCoinContrastsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferCoinContrastsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferCoinContrastsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    int insert(FirmOfferCoinContrasts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferCoinContrasts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    List<FirmOfferCoinContrasts> selectByExample(FirmOfferCoinContrastsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    FirmOfferCoinContrasts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferCoinContrasts record, @Param("example") FirmOfferCoinContrastsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferCoinContrasts record, @Param("example") FirmOfferCoinContrastsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferCoinContrasts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrasts
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferCoinContrasts record);
}