package com.ailu.firmoffer.dao.mapper;

import com.ailu.firmoffer.dao.bean.FirmOfferCoinContrast;
import com.ailu.firmoffer.dao.bean.FirmOfferCoinContrastExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FirmOfferCoinContrastMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    long countByExample(FirmOfferCoinContrastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    int deleteByExample(FirmOfferCoinContrastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    int insert(FirmOfferCoinContrast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    int insertSelective(FirmOfferCoinContrast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    List<FirmOfferCoinContrast> selectByExample(FirmOfferCoinContrastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    FirmOfferCoinContrast selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FirmOfferCoinContrast record, @Param("example") FirmOfferCoinContrastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FirmOfferCoinContrast record, @Param("example") FirmOfferCoinContrastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FirmOfferCoinContrast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table firm_offer_coin_contrast
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FirmOfferCoinContrast record);
}